# OpenVPN服务器配置文件，2026-05-09
#
# 版权所有：Copyright (C) 2024, Martin Young <martin_young@live.cn>
#
# 测试环境：CentOS Stream 10，OpenVPN V2.7
#---------------------------------------------------------------------------

dev tun0

# 为了应对复杂客户端环境，采用多协议多端口混合模式：
local 192.168.255.254 81 udp4          # 根据实际情况修改
local 192.168.255.254 81 tcp4-server   # 根据实际情况修改

# 目前，在CentOS Stream 10这种较新的内核环境下，混合使用UDP(DCO)和TCP(Non-DCO)指向同
# 一个tun0接口，极易触发内核模块ovpn-dco的竞态条件，引发内核恐慌（Kernel Panic）或软锁
# 定（Soft Lockup）问题，因此，应禁用DCO：
disable-dco                 # 如果仅使用单UDP模式，不应禁用DCO

block-ipv6
push "block-ipv6"

ca   ca.crt                 # 根据实际情况修改
cert foo-vpnserver.crt      # 根据实际情况修改
key  foo-vpnserver.key      # 根据实际情况修改

topology subnet
server 192.168.224.0 255.255.240.0  # 根据实际情况修改
ifconfig-pool-persist ipp.txt       # 这个文件自动保存客户端固定分配的IP地址；会在配置文件目录下自动生成
keepalive 10 60

tls-crypt foo-ta.key        # TLS共享密钥；根据实际情况修改。为保障安全性，每1000个用户大约8年需更换一次
tls-ciphersuites TLS_AES_256_GCM_SHA384
tls-version-min 1.2 or-highest	# 针对低版本openvpn客户端（例如在Windows 7或者CentOS 7上）必须允许tls 1.2

max-clients 2000            # 最大并发用户数；根据实际情况修改

persist-tun
push "persist-tun"

status /var/log/openvpn/stat.log 5    # 这个文件自动保存运行时客户端连接状态；根据实际情况修改
status-version 3

log-append /var/log/openvpn/tun0.log  # 日志文件，增量；根据实际情况修改
verb 3                                # 日志级别(0-11)；根据实际情况修改
mute 10
mute-replay-warnings

verify-client-cert none
username-as-common-name
setenv deferred_auth_pam 1
plugin openvpn-plugin-auth-pam.so openvpn.pam   # PAM认证

script-security 3
client-connect on_conn.sh            # 每个客户端连接时都会执行一次这个脚本；根据实际情况修改
#client-disconnect on_disconn.sh      # 每个客户端断开时都会执行一次这个脚本；根据实际情况修改

# 统一虚拟网卡的MTU：
tun-mtu 1400
push "tun-mtu 1400"

# 碎片控制：
mssfix 1360			  # 限制TCP最大段大小（加上40头不超过1400）

# 针对高并发的缓冲区优化（防止1800台设备瞬时流量导致丢包）
# 服务端自身的Socket优化(UDP共享一个，TCP每个用户一个)
sndbuf 1048576
rcvbuf 1048576

# 队列与处理
txqueuelen 2000       # 增加虚拟网卡发送队列长度，匹配2000用户规模

# --- 稳定性与重连优化 ---
# 防重放窗口调大，应对2000人并发时的序列号抖动
# 128 为窗口大小，30 为时间周期（秒）
replay-window 128 30

# 减少 TCP 确认包带来的延迟
# 仅对 TCP 实例生效 (OpenVPN 会自动忽略 UDP 上的此项)
# Linux内核需要设置：net.ipv4.tcp_low_latency = 1
tcp-nodelay

# 提升进程优先级，降低CPU消耗
nice -10
